import type {Metadata} from "next";
import localFont from "next/font/local";
import "../globals.css";
import "reflect-metadata";
import ThemeProvider from "@/providers/theme-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {ReactNode} from "react";
import ScrollTopProvider from "@/context/ScrollTopContext";
import {type Locale} from "@/i18n-config";
import DictionaryProvider from "@/context/DictionaryContext";

const jetbrains = localFont({
    src: [
        {
            path: "../../../public/fonts/Jetbrains/JetBrainsMono-Regular.woff2",
            weight: "400",
            style: "normal"
        },
        {
            path: "../../../public/fonts/Jetbrains/JetBrainsMono-Italic.woff2",
            weight: "400",
            style: "italic"
        },
        {
            path: "../../../public/fonts/Jetbrains/JetBrainsMono-Bold.woff2",
            weight: "700",
            style: "normal"
        },
        {
            path: "../../../public/fonts/Jetbrains/JetBrainsMono-BoldItalic.woff2",
            weight: "700",
            style: "italic"
        },
    ],
    variable: "--font-jetbrains-regular"
});

export const metadata: Metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({children, params}: Readonly<{ children: ReactNode, params: { lang: Locale } }>) {
    return (
        <html lang={params.lang}>
        <body className={`${jetbrains.className} text-[15px] relative`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <ScrollTopProvider>
                <DictionaryProvider locale={params.lang}>
                    <Header/>
                    {children}
                    <Footer/>
                </DictionaryProvider>
            </ScrollTopProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
