import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import "reflect-metadata";
import ThemeProvider from "@/providers/theme-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {ReactNode} from "react";
import ScrollTopProvider from "@/context/ScrollTopContext";

const jetbrains = localFont({
    src: [
        {
            path: "../../public/fonts/Jetbrains/JetBrainsMono-Regular.woff2",
            weight: "400",
            style: "normal"
        },
        {
            path: "../../public/fonts/Jetbrains/JetBrainsMono-Italic.woff2",
            weight: "400",
            style: "italic"
        },
        {
            path: "../../public/fonts/Jetbrains/JetBrainsMono-Bold.woff2",
            weight: "700",
            style: "normal"
        },
        {
            path: "../../public/fonts/Jetbrains/JetBrainsMono-BoldItalic.woff2",
            weight: "700",
            style: "italic"
        },
    ],
    variable: "--font-jetbrains-regular"
});

export const metadata: Metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
        <body className={`${jetbrains.className} text-[15px] relative`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <ScrollTopProvider>
                <Header/>
                {children}
                <Footer/>
            </ScrollTopProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
